### ISSUE TITLE
Not work on very large repo?

### ISSUE THREAD

**Issue by PeterDaveHello** [tomgi/git_stats#48]
I got this error then I try to analyze [cdnjs/cdnjs](https://github.com/cdnjs/cdnjs), this is a really huge repo with more than 10k commits and 11GB disk space usage, I am not sure if this the reason to make the analysis failed, I have no problem with other repos, hope somebody can give me some suggestions, I didn't write code in ruby, so it's hard for me to debug by myself. 

Thanks!

```
git rev-list --pretty=format:'%h|%at|%ai|%aE' HEAD . | grep -v commit
git shortlog -se HEAD .
/var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/command_parser.rb:11:in `scan': invalid byte sequence in UTF-8 (ArgumentError)
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/command_parser.rb:11:in `block in parse_shortlog'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/command_parser.rb:10:in `lines'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/command_parser.rb:10:in `each'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/command_parser.rb:10:in `map'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/command_parser.rb:10:in `parse_shortlog'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/command_parser.rb:6:in `parse'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/git_data/repo.rb:134:in `run_and_parse'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/git_data/repo.rb:43:in `authors'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/git_data/repo.rb:55:in `block in commits'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/git_data/repo.rb:49:in `map'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/git_data/repo.rb:49:in `commits'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/git_data/repo.rb:115:in `activity'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/templates/activity/_activity.haml:97:in `block in singletonclass'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/templates/activity/_activity.haml:65526:in `instance_eval'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/templates/activity/_activity.haml:65526:in `singletonclass'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/templates/activity/_activity.haml:65524:in `__tilt_9709560'
        from /var/lib/gems/1.9.1/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `call'
        from /var/lib/gems/1.9.1/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `evaluate'
        from /var/lib/gems/1.9.1/gems/tilt-2.0.1/lib/tilt/haml.rb:17:in `evaluate'
        from /var/lib/gems/1.9.1/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/stats_view/template.rb:15:in `render'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/stats_view/view_data.rb:18:in `render_partial'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/templates/activity/year_month.haml:1:in `block in singletonclass'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/templates/activity/year_month.haml:65526:in `instance_eval'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/templates/activity/year_month.haml:65526:in `singletonclass'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/templates/activity/year_month.haml:65524:in `__tilt_9709560'
        from /var/lib/gems/1.9.1/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `call'
        from /var/lib/gems/1.9.1/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `evaluate'
        from /var/lib/gems/1.9.1/gems/tilt-2.0.1/lib/tilt/haml.rb:17:in `evaluate'
        from /var/lib/gems/1.9.1/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/stats_view/template.rb:13:in `block in render'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/templates/layout.haml:30:in `block in singletonclass'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/templates/layout.haml:65526:in `instance_eval'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/templates/layout.haml:65526:in `singletonclass'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/templates/layout.haml:65524:in `__tilt_9709560'
        from /var/lib/gems/1.9.1/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `call'
        from /var/lib/gems/1.9.1/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `evaluate'
        from /var/lib/gems/1.9.1/gems/tilt-2.0.1/lib/tilt/haml.rb:17:in `evaluate'
        from /var/lib/gems/1.9.1/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/stats_view/template.rb:13:in `render'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/stats_view/view.rb:15:in `block in render_all'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/stats_view/view.rb:14:in `each'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/stats_view/view.rb:14:in `render_all'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/generator.rb:5:in `render_all'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/lib/git_stats/cli.rb:18:in `generate'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /var/lib/gems/1.9.1/gems/git_stats-1.0.14/bin/git_stats:10:in `<top (required)>'
        from /usr/local/bin/git_stats:23:in `load'
        from /usr/local/bin/git_stats:23:in `<main>'
```

**Comment by PeterDaveHello** [comment]
It works now, just slow. I'll be great if it can runs with multi-thread.
