### ISSUE TITLE
fatal: |: no such path in the working tree.

### ISSUE THREAD

**Issue by XiaofengdiZhu** [tomgi/git_stats#90]
run `git_stats generate` on Windows10 x64:
```
fatal: |: no such path in the working tree.
Use 'git <command> -- <path>...' to specify paths that do not exist locally.
git rev-list --pretty=format:'%H|%at|%ai|%aE' HEAD . | grep -v commit
git shortlog -se HEAD .
D:in `rescue in files_by_extension_count': GitStats::GitData::Repo#files_by_extension_count delegated to last_commit.files_by_extension_count, but last_commit is nil: #<GitStats::GitData::Repo:0x00000000047aa400 @path="G:/Github/SMT3/master", @out_path="./git_stats", @language="en", @last_commit_sha="HEAD", @tree=".", @comment_string="//", @tree_path=".", @command_observers=[#<Proc:0x0000000004c775f0@D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/lib/git_stats/cli.rb:19>], @project_name="master", @command_runner=#<GitStats::CommandRunner:0x0000000004f34f68>, @command_parser=#<GitStats::CommandParser:0x0000000004f34ae0>, @commits=[], @activity=#<GitStats::GitData::Activity:0x0000000004f341f8 @by_date={}, @by_wday={}, @by_hour={}, @by_wday_hour={0=>{}, 1=>{}, 2=>{}, 3=>{}, 4=>{}, 5=>{}, 6=>{}}, @by_month={}, @by_year={}, @by_year_week={}>, @authors=[#<GitStats::GitData::Author:0x0000000004f55628 @repo=#<GitStats::GitData::Repo:0x00000000047aa400 ...>, @name="DESKTOP-O8NAQIV\\admin", @email="523084467@qq.com", @commits=[]>, #<GitStats::GitData::Author:0x0000000004f554c0 @repo=#<GitStats::GitData::Repo:0x00000000047aa400 ...>, @name="XiaofengdiZhu", @email="523084467@qq.com", @commits=[]>, #<GitStats::GitData::Author:0x0000000004f55380 @repo=#<GitStats::GitData::Repo:0x00000000047aa400 ...>, @name="销锋镝铸", @email="523084467@qq.com", @c
ommits=[]>], @comment_count_each_day={}, @files_count_each_day={}> (Module::DelegationError)
        from D:in `files_by_extension_count'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/lib/git_stats/stats_view/charts/repo_charts.rb:13:in `block in files_by_extension'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/lib/git_stats/stats_view/charts/chart.rb:13:in `initialize'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/lib/git_stats/stats_view/charts/repo_charts.rb:11:in `new'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/lib/git_stats/stats_view/charts/repo_charts.rb:11:in `files_by_extension'
        from D:in `files_by_extension'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/templates/files/_files.haml:15:in `block in singleton class'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/templates/files/_files.haml:-2:in `instance_eval'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/templates/files/_files.haml:-2:in `singleton class'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/templates/files/_files.haml:-5:in `__tilt_7109180'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `call'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `evaluate'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/haml.rb:24:in `evaluate'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/lib/git_stats/stats_view/template.rb:15:in `render'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/lib/git_stats/stats_view/view_data.rb:18:in `render_partial'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/templates/files/by_extension.haml:1:in `block in singleton class'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/templates/files/by_extension.haml:-3:in `instance_eval'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/templates/files/by_extension.haml:-3:in `singleton class'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/templates/files/by_extension.haml:-6:in `__tilt_7109180'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `call'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `evaluate'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/haml.rb:24:in `evaluate'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/lib/git_stats/stats_view/template.rb:13:in `block in render'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/templates/layout.haml:32:in `block in singleton class'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/templates/layout.haml:-3:in `instance_eval'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/templates/layout.haml:-3:in `singleton class'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/templates/layout.haml:-6:in `__tilt_7109180'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `call'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `evaluate'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/haml.rb:24:in `evaluate'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/lib/git_stats/stats_view/template.rb:13:in `render'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/lib/git_stats/stats_view/view.rb:15:in `block in render_all'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/lib/git_stats/stats_view/view.rb:14:in `each'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/lib/git_stats/stats_view/view.rb:14:in `render_all'
        from D:in `render_all'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/lib/git_stats/cli.rb:20:in `generate'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from D:/Ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/git_stats-1.0.17/bin/git_stats:10:in `<top (required)>'
        from D:/Ruby/Ruby24-x64/bin/git_stats:23:in `load'
        from D:/Ruby/Ruby24-x64/bin/git_stats:23:in `<main>'
```

**Comment by colonelchlorine** [comment]
Check #77

If you want a quick fix, go to `C:\Ruby24-x64\lib\ruby\gems\2.4.0\gems\git_stats-1.0.17` and change `lib/git_stats/git_data/repo.rb:49` to:

```ruby
@commits ||= run_and_parse("git rev-list --pretty=format:%h^|%at^|%ai^|%aE #{commit_range} #{tree_path} | grep -v commit").map do |commit_line|
```
Also, it's worth fixing the `lib/git_stats/stats_view/view.rb:31` to get the author_details generated:

```ruby
active_page: "authors/#{author.dirname}/#{template}")
```

**Comment by lwfhunter** [comment]
@liushibin @colonelchlorine  I use win server 2012
I tried the quick fix you mentioned but prompted:
'grep' is not recognized as an internal or external command,
operable program or batch file.
